nacos:
  config:
    server-addr: 192.168.180.3:8848
  discovery:
    server-addr: 192.168.180.3:8848
management:
  endpoint:
    health:
      show-details: always
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/graphql_test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456