nacos:
  config:
    server-addr: 192.168.180.3:8848
  discovery:
    server-addr: 192.168.180.3:8848
management:
  endpoint:
    health:
      show-details: always
spring:
  elasticsearch:
    rest:
      uris: 192.168.180.3:9200